### ISSUE TITLE
AMI in eu-west-1 ?

### ISSUE THREAD

**Issue by jerryivanhoe** [bigdatagenomics/eggo#131]
Hi,
running the Cloud Formation in EU-West fails, cause AMI is unknown ? 
[ec2-user@ip-172-31-13-26 ~]$ eggo-cluster provision --region eu-west-1 --launcher-instance-type i2.4xlarge --availability-zone eu-west-1a -n 4
Creating stack with name 'bdg-eggo'.
Waiting for stack to enter 'CREATE_COMPLETE' state..........
Stack is now in 'CREATE_COMPLETE' state. Waited 80 seconds.
Creating launcher instance.
Traceback (most recent call last):
  File "/home/ec2-user/.local/bin/eggo-cluster", line 9, in <module>
    load_entry_point('eggo==0.1.0.dev0', 'console_scripts', 'eggo-cluster')()
  File "/home/ec2-user/.local/lib/python2.7/site-packages/click/core.py", line 700, in **call**
    return self.main(_args, *_kwargs)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ec2-user/.local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(_args, **kwargs)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/eggo/cli/cluster.py", line 76, in provision
    cluster_ami, num_workers)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/eggo/director.py", line 140, in provision
    ec2_conn, cf_conn, stack_name, launcher_ami, launcher_instance_type)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/eggo/director.py", line 92, in create_launcher_instance
    network_interfaces=interfaces)
  File "/usr/lib/python2.7/dist-packages/boto/ec2/connection.py", line 973, in run_instances
    verb='POST')
  File "/usr/lib/python2.7/dist-packages/boto/connection.py", line 1208, in get_object
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidAMIID.NotFound</Code><Message>The image id '[ami-00a11e68]' does not exist</Message></Error></Errors><RequestID>e5f7e623-d8aa-4802-b676-592264a85ee5</RequestID></Response>

Do you have an AMI in Europe ?
greetings
Jerry

**Comment by laserson** [comment]
I have only worked in us-east.  If you run `eggo-cluster provision -h`, you'll see that there are two different AMIs that can be specified.  I believe they're pretty vanilla RHEL 6 AMIs, so should be easy to replace them.

Another note: I notice you're requesting a pretty large instance-type for the launcher.  This node is exclusively there to coordinate the cluster launch, so there is no need to use a high-powered node there.  The worker-instance-type will determine what the actual Hadoop nodes will be.

**Comment by jerryivanhoe** [comment]
oic - yes, switched back to medium :-)
so, the instance just Need to run RedHat 6 ? It's not a special AMI having additional Software inside ?

**Comment by jerryivanhoe** [comment]
it works fine with a "Standard" REHL 6 - used ami "ami-8e96ac93" in eu-central-1

**Comment by laserson** [comment]
Is this still an issue, given your comment in the closed issue?  Perhaps you need RHEL 6.6?

**Comment by jerryivanhoe** [comment]
Hello Uri,
this problem can be solved by running the "eggo-cluster provision " within the same AWS region as the Cluster shall be started. If the regions are different the "password" prompt shows up. So, that's an easy workaround and no further problem for me. Maybe you will see this issue coming back from another user and you may have this workaround at hand. I'm currently stuck with issue 132. From the output it looks as if your script checks the AMI's ID against a fixed list ?!
greetings
Jerry

I called:
eggo-cluster provision --region eu-west-1 --stack-name eggo --launcher-instance-type m3.medium --availability-zone eu-west-1a --launcher-ami ami-8cfc51fb -n 4

**snip**
[52.xx.xx..101] Executing task 'run_director_bootstrap'
 [52.xx.xx..101] put: -> director.conf
 [52.xx.xx..101] run: cloudera-director bootstrap director.conf
 [52.xx.xx..101] out: Process logs can be found at /home/ec2-user/.cloudera-director/logs/application.log
 [52.xx.xx..101] out: Plugins will be loaded from /var/lib/cloudera-director-client/plugins
[52.xx.xx..101] out: Cloudera Director 1.5.1 initializing ...
 [52.xx.xx..101] out: Unexpected internal error (see logs): Validation errors:
 [52.xx.xx..101] out: Invalid AMI: ami-00a11e68Conditions:
 [52.xx.xx..101] out: ValidationExceptionCondition{type=ERROR, scope='aws.com.cloudera.director.aws.ec2.EC2Provider.template', key='Optional.of(image)', message='Invalid AMI: ami-00a11e68'}
 [52.xx.xx..101] out:

Fatal error: run() received nonzero return code 100 while executing!

Requested: cloudera-director bootstrap director.conf
 Executed: /bin/bash -l -c "cloudera-director bootstrap director.conf"

Aborting.
 [ec2-user@ip-172-xx.xx.-26 ~]$
**snap**

**Comment by laserson** [comment]
Ah, it looks like if you specify a launcher AMI in eu-west, then you must also specify a cluster AMI in eu-west.  I'll add an issue to validate that the AMIs are valid in the requested zones.  (presumably boto makes this easy)  Created #134.
