### ISSUE TITLE
No handlers could be found for logger "cm_api.resource"

### ISSUE THREAD

**Issue by jerryivanhoe** [bigdatagenomics/eggo#139]
Hi,
I tried to run eggo-data gen_en_vars un my Cloudera Manager:

eggo-data gen_env_vars --cm-host ip-10-1-1-64.eu-west-1.compute.internal
No handlers could be found for logger "cm_api.resource"
Traceback (most recent call last):
  File "/home/ec2-user/.local/bin/eggo-data", line 9, in <module>
    load_entry_point('eggo==0.1.0.dev0', 'console_scripts', 'eggo-data')()
  File "/home/ec2-user/.local/lib/python2.7/site-packages/click/core.py", line 700, in **call**
    return self.main(_args, *_kwargs)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ec2-user/.local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(_args, **kwargs)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/eggo/cli/datasets.py", line 51, in gen_env_vars
    password)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/eggo/operations.py", line 126, in generate_eggo_env_vars
    info = get_cluster_info(cm_host, cm_port, username, password)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/eggo/operations.py", line 103, in get_cluster_info
    host = list(cm_api.get_all_hosts())[0]  # all hosts same instance type
  File "/home/ec2-user/.local/lib/python2.7/site-packages/cm_api/api_client.py", line 169, in get_all_hosts
    return hosts.get_all_hosts(self, view)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/cm_api/endpoints/hosts.py", line 54, in get_all_hosts
    params=view and dict(view=view) or None)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/cm_api/endpoints/types.py", line 139, in call
    ret = method(path, params=params)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/cm_api/resource.py", line 123, in get
    raise e
urllib2.URLError: <urlopen error [Errno 110] Connection timed out>
[ec2-user@ip-172-31-13-26 ~]$

Any idea ?
greetings
-Jerry

**Comment by jerryivanhoe** [comment]
tried to reproduce with another Cluster : 
and it runs w/o any issue ...

$ eggo-data gen_env_vars --cm-host ip-10-1-1-199.eu-west-1.compute.internal
export EXECUTORS_PER_NODE=4
export MEMORY_PER_EXECUTOR=25807202713
export CORES_PER_EXECUTOR=4
export NUM_WORKER_NODES=4
export NODE_CORES=16
export NODE_MEMORY=129036013568
export TOTAL_EXECUTORS=16
[ec2-user@ip-10-1-1-239 chr1]$

no idea - what's different ....

**Comment by jerryivanhoe** [comment]
could reproduce the issue. does happen, when Connection to master was not done successfully. So-user error - will close this now
