### ISSUE TITLE
VCF2ADAMTask failing because of error with Hadoop-BAM's VCFInputFormat

### ISSUE THREAD

**Issue by laserson** [bigdatagenomics/eggo#65]
Here is the example stacktrace.

```
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3, ip-10-138-100-70.ec2.internal): java.lang.IllegalArgumentException: unknown VCF format, cannot create RecordReader: hdfs://ec2-54-157-172-152.compute-1.amazonaws.com:9000/tmp/tmp_eggo_2015-05-09T00-51-50_AODY.vcf/6a2df5dfbf260f9a0ac9c5270fe27c97.https___github.com_bigdatagenomics_eggo_raw_master_test_resources_chr22.small.vcf
    at org.seqdoop.hadoop_bam.VCFInputFormat.createRecordReader(VCFInputFormat.java:178)
    at org.apache.spark.rdd.NewHadoopRDD$$anon$1.<init>(NewHadoopRDD.scala:133)
    at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:107)
    at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:69)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:280)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:247)
    at org.apache.spark.rdd.FlatMappedRDD.compute(FlatMappedRDD.scala:33)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:280)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:247)
    at org.apache.spark.rdd.FlatMappedRDD.compute(FlatMappedRDD.scala:33)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:280)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:247)
    at org.apache.spark.rdd.MappedRDD.compute(MappedRDD.scala:31)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:280)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:247)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
    at org.apache.spark.scheduler.Task.run(Task.scala:56)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:200)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

I'm guessing we're running into the silenced `IOException` here:
https://github.com/HadoopGenomics/Hadoop-BAM/blob/master/src/main/java/org/seqdoop/hadoop_bam/VCFInputFormat.java#L145

@tomwhite any idea what's going on here?  If you want to reproduce, you should be able to just run my latest branch: laserson/EGGO-62

```
eggo provision
eggo deploy_config
eggo setup_master
eggo setup_slaves
eggo toast:config=$EGGO_HOME/test/registry/test-genotypes.json
```

**Comment by laserson** [comment]
Also, note that the path

```
hdfs://ec2-54-157-172-152.compute-1.amazonaws.com:9000/tmp/tmp_eggo_2015-05-09T00-51-50_AODY.vcf/6a2df5dfbf260f9a0ac9c5270fe27c97.https___github.com_bigdatagenomics_eggo_raw_master_test_resources_chr22.small.vcf
```

is actually a directory, which contains another file called `chr22.small.vcf`.  Can Hadoop-BAM not deal with directories as input paths?

cc @fnothaft

**Comment by laserson** [comment]
And as a final note before I get my shabbos drink on, assuming the path is a directory, would this fail to give a valid `InputStream`?

``` java
path.getFileSystem(conf).open(path)
```

**Comment by fnothaft** [comment]
@laserson From a simple test, Hadoop-BAM _seems_ to be OK here:

```
$ mkdir tmp
$ cp adam-core/src/test/resources/*.vcf tmp/
$ ./bin/adam-submit vcf2adam tmp tmp.var.adam
2015-05-08 18:16:26.199 java[8412:1903] Unable to load realm info from SCDynamicStore
2015-05-08 18:16:26 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
$ ls tmp.var.adam/
_SUCCESS        part-r-00000.gz.parquet part-r-00001.gz.parquet part-r-00002.gz.parquet
```

**Comment by fnothaft** [comment]
@laserson any chance you could post the full command line? I'm testing a few things here and am looking for inspiration.

Also, if you have a recursive dump of the structure of that directory you are loading, that'd be awesome (e.g., `find path/i/am/giving/to/hadoop`, if it were that simple...)

**Comment by laserson** [comment]
So I have the data arranged with an extra directory.

This is the file I'd like to convert:

```
~/tmp/tmp_eggo/tmp2/chr22.small.vcf
```

These two commands succeed on my local machine:

```
./bin/adam-submit vcf2adam ~/tmp/tmp_eggo/tmp2/chr22.small.vcf ~/tmp/tmp_eggo_out5.adam
./bin/adam-submit vcf2adam ~/tmp/tmp_eggo/tmp2 ~/tmp/tmp_eggo_out6.adam
```

This one (analogous to the one I was trying to run on the cluster) fails on my local machine:

```
./bin/adam-submit vcf2adam ~/tmp/tmp_eggo ~/tmp/tmp_eggo_out7.adam

Exception in thread "main" java.lang.NullPointerException
    at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.getBlockIndex(FileInputFormat.java:429)
    at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.getSplits(FileInputFormat.java:400)
    at org.seqdoop.hadoop_bam.VCFInputFormat.getSplits(VCFInputFormat.java:203)
    at org.apache.spark.rdd.NewHadoopRDD.getPartitions(NewHadoopRDD.scala:98)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:222)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:220)
    at scala.Option.getOrElse(Option.scala:120)
    at org.apache.spark.rdd.RDD.partitions(RDD.scala:220)
    at org.apache.spark.rdd.FlatMappedRDD.getPartitions(FlatMappedRDD.scala:30)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:222)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:220)
    at scala.Option.getOrElse(Option.scala:120)
    at org.apache.spark.rdd.RDD.partitions(RDD.scala:220)
    at org.apache.spark.rdd.FlatMappedRDD.getPartitions(FlatMappedRDD.scala:30)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:222)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:220)
    at scala.Option.getOrElse(Option.scala:120)
    at org.apache.spark.rdd.RDD.partitions(RDD.scala:220)
    at org.apache.spark.rdd.MappedRDD.getPartitions(MappedRDD.scala:28)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:222)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:220)
    at scala.Option.getOrElse(Option.scala:120)
    at org.apache.spark.rdd.RDD.partitions(RDD.scala:220)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:1360)
    at org.apache.spark.rdd.PairRDDFunctions.saveAsNewAPIHadoopDataset(PairRDDFunctions.scala:1011)
    at org.apache.spark.rdd.PairRDDFunctions.saveAsNewAPIHadoopFile(PairRDDFunctions.scala:893)
    at org.apache.spark.rdd.InstrumentedPairRDDFunctions.saveAsNewAPIHadoopFile(InstrumentedPairRDDFunctions.scala:466)
    at org.bdgenomics.adam.rdd.ADAMRDDFunctions$$anonfun$adamParquetSave$1.apply$mcV$sp(ADAMRDDFunctions.scala:90)
    at org.bdgenomics.adam.rdd.ADAMRDDFunctions$$anonfun$adamParquetSave$1.apply(ADAMRDDFunctions.scala:71)
    at org.bdgenomics.adam.rdd.ADAMRDDFunctions$$anonfun$adamParquetSave$1.apply(ADAMRDDFunctions.scala:71)
    at org.apache.spark.rdd.Timer.time(Timer.scala:57)
    at org.bdgenomics.adam.rdd.ADAMRDDFunctions.adamParquetSave(ADAMRDDFunctions.scala:71)
    at org.bdgenomics.adam.rdd.ADAMRDDFunctions.adamParquetSave(ADAMRDDFunctions.scala:57)
    at org.bdgenomics.adam.cli.Vcf2ADAM.run(Vcf2ADAM.scala:75)
    at org.bdgenomics.adam.cli.ADAMSparkCommand$class.run(ADAMCommand.scala:57)
    at org.bdgenomics.adam.cli.Vcf2ADAM.run(Vcf2ADAM.scala:54)
    at org.bdgenomics.adam.cli.ADAMMain$.main(ADAMMain.scala:107)
    at org.bdgenomics.adam.cli.ADAMMain.main(ADAMMain.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.spark.deploy.SparkSubmit$.launch(SparkSubmit.scala:358)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:75)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by fnothaft** [comment]
OK, cool. That agrees with what I saw on my machine:

```
$ mkdir tmp
$ mv tmp.vcf/ tmp
$ ./bin/adam-submit vcf2adam tmp tmp.var.adam.2
2015-05-08 18:25:39.833 java[8696:1903] Unable to load realm info from SCDynamicStore
2015-05-08 18:25:39 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
^X^Czziriszz:adam fnothaft$ ./bin/adam-submit vcf2adam tmp tmp.var.adam.3
2015-05-08 18:25:43.538 java[8752:1903] Unable to load realm info from SCDynamicStore
2015-05-08 18:25:43 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2015-05-08 18:25:45 ERROR ADAMRDDFunctions:75 - Filename does not end with *.adam extension. File will be saved, but must be renamed to be opened.
Exception in thread "main" java.lang.NullPointerException
    at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.getBlockIndex(FileInputFormat.java:390)
    at org.apache.hadoop.mapreduce.lib.input.FileInputFormat.getSplits(FileInputFormat.java:365)
    at org.seqdoop.hadoop_bam.VCFInputFormat.getSplits(VCFInputFormat.java:203)
    at org.apache.spark.rdd.NewHadoopRDD.getPartitions(NewHadoopRDD.scala:95)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:219)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:217)
    at scala.Option.getOrElse(Option.scala:120)
    at org.apache.spark.rdd.RDD.partitions(RDD.scala:217)
    at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:32)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:219)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:217)
    at scala.Option.getOrElse(Option.scala:120)
    at org.apache.spark.rdd.RDD.partitions(RDD.scala:217)
    at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:32)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:219)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:217)
    at scala.Option.getOrElse(Option.scala:120)
    at org.apache.spark.rdd.RDD.partitions(RDD.scala:217)
    at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:32)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:219)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:217)
    at scala.Option.getOrElse(Option.scala:120)
    at org.apache.spark.rdd.RDD.partitions(RDD.scala:217)
    at org.apache.spark.SparkContext.runJob(SparkContext.scala:1505)
    at org.apache.spark.rdd.PairRDDFunctions.saveAsNewAPIHadoopDataset(PairRDDFunctions.scala:1019)
    at org.apache.spark.rdd.PairRDDFunctions.saveAsNewAPIHadoopFile(PairRDDFunctions.scala:903)
    at org.apache.spark.rdd.InstrumentedPairRDDFunctions.saveAsNewAPIHadoopFile(InstrumentedPairRDDFunctions.scala:466)
    at org.bdgenomics.adam.rdd.ADAMRDDFunctions$$anonfun$adamParquetSave$1.apply$mcV$sp(ADAMRDDFunctions.scala:90)
    at org.bdgenomics.adam.rdd.ADAMRDDFunctions$$anonfun$adamParquetSave$1.apply(ADAMRDDFunctions.scala:71)
    at org.bdgenomics.adam.rdd.ADAMRDDFunctions$$anonfun$adamParquetSave$1.apply(ADAMRDDFunctions.scala:71)
    at org.apache.spark.rdd.Timer.time(Timer.scala:57)
    at org.bdgenomics.adam.rdd.ADAMRDDFunctions.adamParquetSave(ADAMRDDFunctions.scala:71)
    at org.bdgenomics.adam.rdd.ADAMRDDFunctions.adamParquetSave(ADAMRDDFunctions.scala:57)
    at org.bdgenomics.adam.cli.Vcf2ADAM.run(Vcf2ADAM.scala:75)
    at org.bdgenomics.adam.cli.ADAMSparkCommand$class.run(ADAMCommand.scala:57)
    at org.bdgenomics.adam.cli.Vcf2ADAM.run(Vcf2ADAM.scala:54)
    at org.bdgenomics.adam.cli.ADAMMain$.main(ADAMMain.scala:107)
    at org.bdgenomics.adam.cli.ADAMMain.main(ADAMMain.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:569)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:166)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:189)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:110)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
$
```

I'll go through this in a bit more detail tomorrow. The NPE is different from the IAE you're getting on a cluster, which is interesting.

**Comment by laserson** [comment]
This test will repro locally:

``` scala
sparkTest("blah") {
    // Succeeds:
    // val adamVariants: RDD[VariantContext] = sc.loadVcf("/Users/laserson/tmp/tmp_eggo/tmp2/chr22.small.vcf", None)

    // Succeeds:
    // val adamVariants: RDD[VariantContext] = sc.loadVcf("/Users/laserson/tmp/tmp_eggo/tmp2", None)

    // Fails:
    val adamVariants: RDD[VariantContext] = sc.loadVcf("/Users/laserson/tmp/tmp_eggo", None)

    println(adamVariants.count())
    assert(adamVariants.count() == 70)
}
```

**Comment by laserson** [comment]
I think we need to set `mapreduce.input.fileinputformat.input.dir.recursive` to `"true"` as a fix.  But this should probably be user-defined to keep with the usual `FileInputFormat` semantics.

**Comment by fnothaft** [comment]
Does it succeed if you run with `-conf mapreduce.input.fileinputformat.input.dir.recursive=true`?

**Comment by laserson** [comment]
Test just passed for me with this snippet

``` scala
    sc.stop()
    val conf = new SparkConf(false)
      .setAppName("MultilevelDir")
      .setMaster("local[1]")
      .set("spark.hadoop.mapreduce.input.fileinputformat.input.dir.recursive", "true")  // FileInputFormat.INPUT_DIR_RECURSIVE / mapreduce.input.fileinputformat.input.dir.recursive
    val sc2 = new SparkContext(conf)
    val adamVariants: RDD[VariantContext] = sc2.loadVcf("/Users/laserson/tmp/tmp_eggo", None)

    println(adamVariants.count())
    assert(adamVariants.count() == 70)
```

**Comment by laserson** [comment]
So yeah, probably just need to set that property...I'll try it on the cluster later tonight or tomorrow.

**Comment by fnothaft** [comment]
Yeah, looks good here too:

```
$ export ADAM_OPTS="--conf spark.hadoop.mapreduce.input.fileinputformat.input.dir.recursive=true"
$ ./bin/adam-submit vcf2adam tmp tmp.var.adam.5
2015-05-10 07:59:13.210 java[10586:1903] Unable to load realm info from SCDynamicStore
2015-05-10 07:59:13 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2015-05-10 07:59:17 ERROR ADAMRDDFunctions:75 - Filename does not end with *.adam extension. File will be saved, but must be renamed to be opened.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
$
```

**Comment by laserson** [comment]
Hmm, setting the flag doesn't seem to solve this problem when I test on the cluster.  The cluster is provisioned with the spark-ec2 scripts.  This command will work (as I specify one directory deeper than I'd like)

```
bin/adam-submit --master $SPARK_MASTER_URI vcf2adam /tmp/tmp_eggo_2015-05-11T07-33-18_FTLY.vcf/6a2df5dfbf260f9a0ac9c5270fe27c97.https___github.com_bigdatagenomics_eggo_raw_master_test_resources_chr22.small.vcf s3n://bdg-eggo/test-geno-4
```

but this command fails

```
bin/adam-submit --conf spark.hadoop.mapreduce.input.fileinputformat.input.dir.recursive=true --master $SPARK_MASTER_URI vcf2adam /tmp/tmp_eggo_2015-05-11T07-33-18_FTLY.vcf s3n://bdg-eggo/test-geno-5
```

In terms of versions, I am using Spark 1.2 built against Hadoop 2.4.  ADAM itself specifies a "provided" dependency on Hadoop 2.2.  And the cluster itself installs Hadoop 1.0.4.  Which version of the code is actually getting run?

Setting `mapred.input.dir.recursive=true` (MAPREDUCE-1501) doesn't help either.  Thoughts, @tomwhite?  Is this simply a matter of matching all the Hadoop versions to each other?

**Comment by tomwhite** [comment]
The new MR API in Hadoop 1 (org.apache.hadoop.mapreduce.lib.input.FileInputFormat) doesn't support recursive listing, so that might be what's happening. The old version of MR on Spark-EC2 is annoying, although I thought it wasn't picked up if you are using Spark. The other thing to try is set the EC2 scripts to use Hadoop 2.

**Comment by laserson** [comment]
Closing this bc we decided that depending on recursive traversal of input directories is probably a worse idea than not depending on it.
